#!/bin/bash

# FPM ip and port
#sed -i "s/%socket_uri%/$SOCKET_URI/" /etc/php5/fpm/pool.d/api0.conf
#sed -i "s/%proxy-port%/$NGINX_PORT_80_TCP_PORT/" /etc/php5/fpm/pool.d/api0.conf
#sed -i "s/%fpm-port%/$FPM_PORT/" /etc/php5/fpm/pool.d/api0.conf

export COMPOSER_HOME=/var/www/;

if [ -d "/var/www/public" ]; then

    echo "Skipping Apigility install"

else

	cd /var/www/ && curl -sS https://getcomposer.org/installer | php
	cd /var/www/ && php composer.phar create-project -sdev zfcampus/zf-apigility-skeleton
	cd /var/www/ && php composer.phar install

	mv /var/www/zf-apigility-skeleton/* /var/www/
	rm -rf /var/www/zf-apigility-skeleton

	cd /var/www/ && php public/index.php development enable

fi

rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/php-fpm /etc/nginx/sites-enabled/

service php5-fpm start
service nginx start